name: Build KB (Notion → JSONL)

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - "scripts/**"
      - "kb_mapping.yaml"
      - ".github/workflows/build_kb.yml"

permissions:
  contents: write

env:
  NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
  NOTION_DB_ID: ${{ secrets.NOTION_DB_ID }}
  RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}

jobs:
  build-kb:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pyyaml

      - name: Build kb.jsonl from Notion
        run: |
          echo "[INFO] start build_kb.py"
          python scripts/build_kb.py \
            --db-id "$NOTION_DB_ID" \
            --token "$NOTION_TOKEN" \
            --mapping "kb_mapping.yaml" \
            --out "kb.jsonl" \
            --validate-title-contains "コンテスト結果>=6"

      - name: Show summary
        run: |
          echo "---- head ----"; head -n 3 kb.jsonl || true
          echo "---- stats ----"; wc -l kb.jsonl || true
          sha256sum kb.jsonl || true

      - name: Commit & push if changed
        run: |
          git config user.name  "actions-user"
          git config user.email "actions@users.noreply.github.com"
          git add kb.jsonl
          if ! git diff --cached --quiet; then
            git commit -m "Auto update KB ${{ github.run_id }}"
            git push
          else
            echo "No changes in kb.jsonl"
          fi

      - name: Trigger Render deploy (optional)
        if: ${{ env.RENDER_DEPLOY_HOOK != '' }}
        run: |
          curl -fsSL -X POST "$RENDER_DEPLOY_HOOK" || true
