name: Keep Render Awake

on:
  schedule:
    - cron: '*/15 * * * *'   # 15分ごと（Freeプランのスリープ対策）
  workflow_dispatch:         # 手動実行ボタンも付ける

jobs:
  ping:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Ping Render /health
        run: |
          curl -fsS https://mini-rose-search-jsonl.onrender.com/health || exit 1
