name: Verify Health (Deep)

on:
  schedule:
    - cron: '0 * * * *'      # 毎時00分に1回（UTC）
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    env:
      BASE_URL: https://mini-rose-search-jsonl.onrender.com
      UA: "curl/verify (GitHub Actions)"

    steps:
      - name: Show schedule (UTC)
        run: date -u +"UTC %Y-%m-%d %H:%M:%S"

      - name: Wake (no-fail)
        run: |
          curl -fsS -m 15 -o /dev/null -A "$UA" "$BASE_URL/health" || true

      - name: Warm-up (<=120s)
        shell: bash
        run: |
          SECS=0
          until curl -fsS --retry 12 --retry-delay 10 --retry-connrefused -m 10 -o /dev/null "$BASE_URL/health"; do
            SECS=$((SECS+10))
            echo "  waking... ${SECS}s"
            [ $SECS -ge 120 ] && break
          done

      - name: Verify /health == 200 (<=6m)
        shell: bash
        run: |
          ATTEMPTS=36
          for i in $(seq 1 $ATTEMPTS); do
            code=$(curl -s -o /dev/null -w "%{http_code}" -A "$UA" --max-time 10 "$BASE_URL/health" || echo "000")
            echo "  [$i/$ATTEMPTS] /health -> $code"
            [ "$code" = "200" ] && exit 0
            sleep 10
          done
          echo "NG: /health not 200 in $((ATTEMPTS*10))s"
          exit 1

      - name: Check UI (no-fail)
        run: |
          curl -fsS -m 20 -A "$UA" "$BASE_URL/ui" -o /dev/null || true
