name: Keep Render Awake

on:
  schedule:
    - cron: '*/10 * * * *'   # 10分ごと（UTC）
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    timeout-minutes: 8

    env:
      BASE_URL: https://mini-rose-search-jsonl.onrender.com
      UA: "curl/keep-awake (GitHub Actions)"

    steps:
      - name: Show schedule (UTC)
        run: date -u +"UTC %Y-%m-%d %H:%M:%S"

      # 1) Wake: /health に長めヒット（ここでは失敗扱いにしない）
      - name: Wake (hit /health, no-fail)
        run: |
          curl --location --show-error \
               --max-time 90 --connect-timeout 20 \
               -H "User-Agent: $UA" -H "Accept: application/json" \
               "$BASE_URL/health" || true

      # 2) Verify: /health が 200 になるまで最大2分ポーリング
      - name: Verify health (poll until 200)
        shell: bash
        run: |
          for i in {1..12}; do
            code=$(curl -s -o /dev/null -w "%{http_code}" \
                    -H "User-Agent: $UA" -H "Accept: application/json" \
                    --max-time 10 --connect-timeout 5 \
                    "$BASE_URL/health" || echo "000")
            echo "[$i] /health -> HTTP $code"
            if [ "$code" = "200" ]; then
              echo "OK: service is up."
              exit 0
            fi
            sleep 10
          done
          echo "NG: /health did not return 200 within 120s."
          exit 1

      # 3)（任意）UIの到達性チェック：失敗してもワークフローを落とさない
      - name: Check UI (no-fail)
        run: |
          curl -I --location --show-error \
               --max-time 30 --connect-timeout 10 \
               -H "User-Agent: $UA" -H "Accept: text/html" \
               "$BASE_URL/ui" || true
