name: Verify Health (Light, No-Fail)

on:
  schedule:
    - cron: '0 * * * *'      # 毎時00分（UTC）＝ JSTで毎時09分
  workflow_dispatch:          # 手動実行も可能

jobs:
  verify:
    runs-on: ubuntu-latest
    timeout-minutes: 5        # 強制終了までの上限時間（短め）

    env:
      BASE_URL: https://mini-rose-search-jsonl.onrender.com
      UA: "curl/verify-health (GitHub Actions)"

    steps:
      - name: Show schedule (UTC)
        run: date -u +"UTC %Y-%m-%d %H:%M:%S"

      # 1回目〜3回目まで合計60秒ほど待ちつつ再試行（Render起動中を想定）
      - name: Poll /health for 200 (max 3 attempts, <=60s)
        shell: bash
        continue-on-error: true
        run: |
          echo "[Verify] Checking /health (<=3 tries)"
          for i in 1 2 3; do
            code=$(curl -4 -s -o /dev/null -w "%{http_code}" \
                    -A "$UA" --max-time 10 --connect-timeout 3 \
                    "$BASE_URL/health" || echo "000")
            echo "  [$i/3] HTTP $code"
            [ "$code" = "200" ] && { echo "OK: 200 received"; exit 0; }
            sleep 20
          done
          echo "WARN: /health did not return 200 (no-fail)"

      # UI到達確認（軽いGET、失敗してもOK）
      - name: Check /ui (GET, no-fail)
        shell: bash
        continue-on-error: true
        run: |
          curl -4 -sS -m 8 --connect-timeout 3 -A "$UA" \
               "$BASE_URL/ui" -o /dev/null || echo "WARN: /ui not reachable"

      # すべて成功扱いで終了（通知メール防止）
      - name: Mark success (always)
        run: echo "Done (verify-health, no-fail)."
